name: UI types
runs:
  using: "composite"
  steps:
    - name: Cache UI types
      id: cache-ui-types
      uses: actions/cache@v4
      with:
        path: |
          ui/packages/evidently-ui-lib/src/api/types/endpoints.d.ts
        key: ui-types-${{ runner.os }}-${{ hashFiles('./.github/**', './src/evidently/**', '!src/evidently/**/ui/**/assets/**', '!src/evidently/nbextension/**') }}

    - uses: actions/setup-python@v5
      if: steps.cache-ui-types.outputs.cache-hit != 'true'
      with:
        python-version: "3.11"
        architecture: "x64"
#        cache: "pip"

    - name: Install Evidently
      if: steps.cache-ui-types.outputs.cache-hit != 'true'
      run: pip install -e .
      shell: bash

    - name: Calculate types
      if: steps.cache-ui-types.outputs.cache-hit != 'true'
      run: |
        litestar --app evidently.ui.service.app:litestar_app schema openapi --output evidently-openapi-schema.yml
        npx openapi-typescript@6 ./evidently-openapi-schema.yml -o ui/packages/evidently-ui-lib/src/api/types/endpoints.d.ts
      shell: bash
