from .non_letter_character_percentage_descriptor import NonLetterCharacterPercentage
from .oov_words_percentage_descriptor import OOV
from .text_length_descriptor import TextLength
from .trigger_words_presence_descriptor import TriggerWordsPresence
