{
 "title": "Evidently Numerical Target Drift",
 "time": { "from": "2023-04-07T09:39:35.085Z", "to": "2023-04-07T09:45:09.888Z" },
 "panels": [
  {
   "title": "Stattest Name",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  MAX(stattest_name)\nFROM\n  target_drift"
    }
   ]
  },
  {
   "title": "Stattest Threshold",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  stattest_threshold\nFROM\n  target_drift\n"
    }
   ]
  },
  {
   "title": "Rows Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "legendFormat": "{{dataset}}",
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  number_of_rows\nFROM data_quality"
    }
   ]
  },
  {
   "title": "Target Drift",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  drift_detected::int\nFROM\n  target_drift\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Drift Score (p-value)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  drift_score,\n  stattest_threshold\nFROM\n  target_drift\nORDER BY 1"
    }
   ]
  }
 ]
}