{
 "title": "Evidently Regression Performance Dashboard",
 "time": { "from": "2023-04-10T10:41:19.671Z", "to": "2023-04-10T10:43:28.354Z" },
 "panels": [
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "ME",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "legendFormat": "ME",
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  mean_error\nFROM model_performance\nORDER BY 1"
    }
   ]
  },
  {
   "title": "MAE",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "legendFormat": "ME",
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  mean_abs_error\nFROM model_performance\nORDER BY 1"
    }
   ]
  },
  {
   "title": "MAPE",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  mean_abs_perc_error\nFROM model_performance\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Aggregated Metrics in time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "legendFormat": "ME",
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  mean_error AS \"ME\"\nFROM model_performance\nORDER BY 1"
    },
    {
     "legendFormat": "MAE",
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  mean_abs_error AS \"MAE\"\nFROM model_performance\nORDER BY 1"
    }
   ]
  },
  {
   "title": "MAPE",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "legendFormat": "MAPE",
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  mean_abs_perc_error AS \"MAPE\"\nFROM model_performance\nORDER BY 1"
    }
   ]
  }
 ]
}