{{- if and .Values.s3.enabled (not .Values.s3.existingSecret.name) .Values.s3.accessKey .Values.s3.secretKey -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "evidently-ui.fullname" . }}-s3
  labels:
    {{- include "evidently-ui.labels" . | nindent 4 }}
type: Opaque
data:
  access-key: {{ .Values.s3.accessKey | b64enc | quote }}
  secret-key: {{ .Values.s3.secretKey | b64enc | quote }}
{{- end -}}
