/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


/** OneOf type helpers */
type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };
type XOR<T, U> = (T | U) extends object ? (Without<T, U> & U) | (Without<U, T> & T) : T | U;
type OneOf<T extends any[]> = T extends [infer Only] ? Only : T extends [infer A, infer B, ...infer Rest] ? OneOf<[XOR<A, B>, ...Rest]> : never;

export interface paths {
  "/api/projects": {
    /** ListProjects */
    get: operations["ApiProjectsListProjects"];
    /** AddProject */
    post: operations["ApiProjectsAddProject"];
  };
  "/api/projects/models/additional": {
    /** AdditionalModels */
    get: operations["ApiProjectsModelsAdditionalAdditionalModels"];
  };
  "/api/projects/search/{project_name}": {
    /** SearchProjects */
    get: operations["ApiProjectsSearchProjectNameSearchProjects"];
  };
  "/api/projects/{project_id}": {
    /** DeleteProject */
    delete: operations["ApiProjectsProjectIdDeleteProject"];
  };
  "/api/projects/{project_id}/dashboard": {
    /** ProjectDashboard */
    get: operations["ApiProjectsProjectIdDashboardProjectDashboard"];
  };
  "/api/projects/{project_id}/dashboard/panels": {
    /** ListProjectDashboardPanels */
    get: operations["ApiProjectsProjectIdDashboardPanelsListProjectDashboardPanels"];
  };
  "/api/projects/{project_id}/info": {
    /** GetProjectInfo */
    get: operations["ApiProjectsProjectIdInfoGetProjectInfo"];
    /** UpdateProjectInfo */
    post: operations["ApiProjectsProjectIdInfoUpdateProjectInfo"];
  };
  "/api/projects/{project_id}/reload": {
    /** ReloadProjectSnapshots */
    get: operations["ApiProjectsProjectIdReloadReloadProjectSnapshots"];
  };
  "/api/projects/{project_id}/reports": {
    /** ListReports */
    get: operations["ApiProjectsProjectIdReportsListReports"];
  };
  "/api/projects/{project_id}/snapshots": {
    /** AddSnapshot */
    post: operations["ApiProjectsProjectIdSnapshotsAddSnapshot"];
  };
  "/api/projects/{project_id}/test_suites": {
    /** ListTestSuites */
    get: operations["ApiProjectsProjectIdTestSuitesListTestSuites"];
  };
  "/api/projects/{project_id}/{snapshot_id}": {
    /** DeleteSnapshot */
    delete: operations["ApiProjectsProjectIdSnapshotIdDeleteSnapshot"];
  };
  "/api/projects/{project_id}/{snapshot_id}/data": {
    /** GetSnapshotData */
    get: operations["ApiProjectsProjectIdSnapshotIdDataGetSnapshotData"];
  };
  "/api/projects/{project_id}/{snapshot_id}/download": {
    /** GetSnapshotDownload */
    get: operations["ApiProjectsProjectIdSnapshotIdDownloadGetSnapshotDownload"];
  };
  "/api/projects/{project_id}/{snapshot_id}/graphs_data/{graph_id}": {
    /** GetSnapshotGraphData */
    get: operations["ApiProjectsProjectIdSnapshotIdGraphsDataGraphIdGetSnapshotGraphData"];
  };
  "/api/version": {
    /** Version */
    get: operations["ApiVersionVersion"];
  };
  "/{file_path}": {
    /** GetHandler */
    get: operations["FilePathGetHandler"];
    /** HeadHandler */
    head: operations["FilePathHeadHandler"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** DashboardConfig */
    DashboardConfig: {
      name: string;
      panels: components["schemas"]["DashboardPanel"][];
      /** @default {} */
      tab_id_to_panel_ids?: OneOf<[null, {
        [key: string]: string[];
      }]>;
      /** @default [] */
      tabs?: null | components["schemas"]["DashboardTab"][];
    };
    /** DashboardInfoModel */
    DashboardInfoModel: {
      max_timestamp?: null | string;
      min_timestamp?: null | string;
      name: string;
      widgets: unknown[];
    };
    /** DashboardPanel */
    DashboardPanel: {
      filter: components["schemas"]["ReportFilter"];
      id?: null | string;
      /**
       * @default 2
       * @enum {integer|null}
       */
      size?: 1 | 2 | null;
      title: string;
      /** @default */
      type?: null | string;
    };
    /** DashboardPanelCounter */
    DashboardPanelCounter: {
      /** @enum {string} */
      agg: "sum" | "last" | "none";
      filter: components["schemas"]["ReportFilter"];
      id?: null | string;
      /**
       * @default 2
       * @enum {integer|null}
       */
      size?: 1 | 2 | null;
      text?: null | string;
      title: string;
      /** @default */
      type?: null | string;
      value?: null | components["schemas"]["PanelValue"];
    };
    /** DashboardPanelPlot */
    DashboardPanelPlot: {
      filter: components["schemas"]["ReportFilter"];
      id?: null | string;
      /** @enum {string} */
      plot_type: "scatter" | "bar" | "line" | "histogram";
      /**
       * @default 2
       * @enum {integer|null}
       */
      size?: 1 | 2 | null;
      title: string;
      /** @default */
      type?: null | string;
      values: components["schemas"]["PanelValue"][];
    };
    /** DashboardTab */
    DashboardTab: {
      id?: null | string;
      /** @default Untitled */
      title?: null | string;
    };
    /** EvidentlyBaseModel */
    EvidentlyBaseModel: {
      /** @default */
      type?: null | string;
    };
    /** MetricModel */
    MetricModel: {
      id: string;
    };
    /** PanelValue */
    PanelValue: {
      field_path: unknown;
      legend?: null | string;
      /** @default {} */
      metric_args?: OneOf<[null, {
        [key: string]: unknown;
      }]>;
      metric_hash?: null | string;
      metric_id?: null | string;
    };
    /** Project */
    Project: {
      created_at?: null | string;
      dashboard?: null | components["schemas"]["DashboardConfig"];
      date_from?: null | string;
      date_to?: null | string;
      description?: null | string;
      id?: null | string;
      name: string;
      team_id?: null | string;
    };
    /** ReportFilter */
    ReportFilter: {
      /** @default false */
      include_test_suites?: null | boolean;
      metadata_values: {
        [key: string]: string;
      };
      tag_values: string[];
    };
    /** ReportModel */
    ReportModel: {
      /** Format: uuid */
      id: string;
      metadata: {
        [key: string]: OneOf<[string, {
          [key: string]: string;
        }, string[]]>;
      };
      metrics: components["schemas"]["MetricModel"][];
      tags: string[];
      /** Format: date-time */
      timestamp: string;
    };
    /** TestSuiteModel */
    TestSuiteModel: {
      /** Format: uuid */
      id: string;
      metadata: {
        [key: string]: OneOf<[string, {
          [key: string]: string;
        }, string[]]>;
      };
      tags: string[];
      /** Format: date-time */
      timestamp: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** ListProjects */
  ApiProjectsListProjects: {
    responses: {
      /** @description Request fulfilled, document follows */
      200: {
        headers: {
        };
        content: {
          "application/json": components["schemas"]["Project"][];
        };
      };
    };
  };
  /** AddProject */
  ApiProjectsAddProject: {
    parameters: {
      query?: {
        team_id?: null | string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Project"];
      };
    };
    responses: {
      /** @description Document created, URL follows */
      201: {
        headers: {
        };
        content: {
          "application/json": components["schemas"]["Project"];
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        content: {
          "application/json": {
            detail: string;
            extra?: null | {
              [key: string]: unknown;
            } | unknown[];
            status_code: number;
          };
        };
      };
    };
  };
  /** AdditionalModels */
  ApiProjectsModelsAdditionalAdditionalModels: {
    responses: {
      /** @description Request fulfilled, document follows */
      200: {
        headers: {
        };
        content: {
          "application/json": (components["schemas"]["DashboardInfoModel"] | components["schemas"]["DashboardPanelPlot"] | components["schemas"]["DashboardPanelCounter"])[];
        };
      };
    };
  };
  /** SearchProjects */
  ApiProjectsSearchProjectNameSearchProjects: {
    parameters: {
      path: {
        project_name: string;
      };
    };
    responses: {
      /** @description Request fulfilled, document follows */
      200: {
        headers: {
        };
        content: {
          "application/json": components["schemas"]["Project"][];
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        content: {
          "application/json": {
            detail: string;
            extra?: null | {
              [key: string]: unknown;
            } | unknown[];
            status_code: number;
          };
        };
      };
    };
  };
  /** DeleteProject */
  ApiProjectsProjectIdDeleteProject: {
    parameters: {
      path: {
        project_id: string;
      };
    };
    responses: {
      /** @description Request fulfilled, nothing follows */
      204: {
        headers: {
        };
        content: never;
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        content: {
          "application/json": {
            detail: string;
            extra?: null | {
              [key: string]: unknown;
            } | unknown[];
            status_code: number;
          };
        };
      };
    };
  };
  /** ProjectDashboard */
  ApiProjectsProjectIdDashboardProjectDashboard: {
    parameters: {
      query?: {
        timestamp_start?: null | string;
        timestamp_end?: null | string;
      };
      path: {
        project_id: string;
      };
    };
    responses: {
      /** @description Request fulfilled, document follows */
      200: {
        headers: {
        };
        content: {
          "text/plain": string;
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        content: {
          "application/json": {
            detail: string;
            extra?: null | {
              [key: string]: unknown;
            } | unknown[];
            status_code: number;
          };
        };
      };
    };
  };
  /** ListProjectDashboardPanels */
  ApiProjectsProjectIdDashboardPanelsListProjectDashboardPanels: {
    parameters: {
      path: {
        project_id: string;
      };
    };
    responses: {
      /** @description Request fulfilled, document follows */
      200: {
        headers: {
        };
        content: {
          "application/json": components["schemas"]["DashboardPanel"][];
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        content: {
          "application/json": {
            detail: string;
            extra?: null | {
              [key: string]: unknown;
            } | unknown[];
            status_code: number;
          };
        };
      };
    };
  };
  /** GetProjectInfo */
  ApiProjectsProjectIdInfoGetProjectInfo: {
    parameters: {
      path: {
        project_id: string;
      };
    };
    responses: {
      /** @description Request fulfilled, document follows */
      200: {
        headers: {
        };
        content: {
          "application/json": components["schemas"]["Project"];
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        content: {
          "application/json": {
            detail: string;
            extra?: null | {
              [key: string]: unknown;
            } | unknown[];
            status_code: number;
          };
        };
      };
    };
  };
  /** UpdateProjectInfo */
  ApiProjectsProjectIdInfoUpdateProjectInfo: {
    parameters: {
      path: {
        project_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Project"];
      };
    };
    responses: {
      /** @description Document created, URL follows */
      201: {
        headers: {
        };
        content: {
          "application/json": components["schemas"]["Project"];
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        content: {
          "application/json": {
            detail: string;
            extra?: null | {
              [key: string]: unknown;
            } | unknown[];
            status_code: number;
          };
        };
      };
    };
  };
  /** ReloadProjectSnapshots */
  ApiProjectsProjectIdReloadReloadProjectSnapshots: {
    parameters: {
      path: {
        project_id: string;
      };
    };
    responses: {
      /** @description Request fulfilled, document follows */
      200: {
        headers: {
        };
        content: never;
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        content: {
          "application/json": {
            detail: string;
            extra?: null | {
              [key: string]: unknown;
            } | unknown[];
            status_code: number;
          };
        };
      };
    };
  };
  /** ListReports */
  ApiProjectsProjectIdReportsListReports: {
    parameters: {
      path: {
        project_id: string;
      };
    };
    responses: {
      /** @description Request fulfilled, document follows */
      200: {
        headers: {
        };
        content: {
          "application/json": components["schemas"]["ReportModel"][];
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        content: {
          "application/json": {
            detail: string;
            extra?: null | {
              [key: string]: unknown;
            } | unknown[];
            status_code: number;
          };
        };
      };
    };
  };
  /** AddSnapshot */
  ApiProjectsProjectIdSnapshotsAddSnapshot: {
    parameters: {
      path: {
        project_id: string;
      };
    };
    responses: {
      /** @description Document created, URL follows */
      201: {
        headers: {
        };
        content: never;
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        content: {
          "application/json": {
            detail: string;
            extra?: null | {
              [key: string]: unknown;
            } | unknown[];
            status_code: number;
          };
        };
      };
    };
  };
  /** ListTestSuites */
  ApiProjectsProjectIdTestSuitesListTestSuites: {
    parameters: {
      path: {
        project_id: string;
      };
    };
    responses: {
      /** @description Request fulfilled, document follows */
      200: {
        headers: {
        };
        content: {
          "application/json": components["schemas"]["TestSuiteModel"][];
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        content: {
          "application/json": {
            detail: string;
            extra?: null | {
              [key: string]: unknown;
            } | unknown[];
            status_code: number;
          };
        };
      };
    };
  };
  /** DeleteSnapshot */
  ApiProjectsProjectIdSnapshotIdDeleteSnapshot: {
    parameters: {
      path: {
        project_id: string;
        snapshot_id: string;
      };
    };
    responses: {
      /** @description Request fulfilled, nothing follows */
      204: {
        headers: {
        };
        content: never;
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        content: {
          "application/json": {
            detail: string;
            extra?: null | {
              [key: string]: unknown;
            } | unknown[];
            status_code: number;
          };
        };
      };
    };
  };
  /** GetSnapshotData */
  ApiProjectsProjectIdSnapshotIdDataGetSnapshotData: {
    parameters: {
      path: {
        project_id: string;
        snapshot_id: string;
      };
    };
    responses: {
      /** @description Request fulfilled, document follows */
      200: {
        headers: {
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        content: {
          "application/json": {
            detail: string;
            extra?: null | {
              [key: string]: unknown;
            } | unknown[];
            status_code: number;
          };
        };
      };
    };
  };
  /** GetSnapshotDownload */
  ApiProjectsProjectIdSnapshotIdDownloadGetSnapshotDownload: {
    parameters: {
      query?: {
        report_format?: string;
      };
      path: {
        project_id: string;
        snapshot_id: string;
      };
    };
    responses: {
      /** @description Request fulfilled, document follows */
      200: {
        headers: {
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        content: {
          "application/json": {
            detail: string;
            extra?: null | {
              [key: string]: unknown;
            } | unknown[];
            status_code: number;
          };
        };
      };
    };
  };
  /** GetSnapshotGraphData */
  ApiProjectsProjectIdSnapshotIdGraphsDataGraphIdGetSnapshotGraphData: {
    parameters: {
      path: {
        project_id: string;
        snapshot_id: string;
        graph_id: string;
      };
    };
    responses: {
      /** @description Request fulfilled, document follows */
      200: {
        headers: {
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        content: {
          "application/json": {
            detail: string;
            extra?: null | {
              [key: string]: unknown;
            } | unknown[];
            status_code: number;
          };
        };
      };
    };
  };
  /** Version */
  ApiVersionVersion: {
    responses: {
      /** @description Request fulfilled, document follows */
      200: {
        headers: {
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  /** GetHandler */
  FilePathGetHandler: {
    parameters: {
      path: {
        file_path: unknown;
      };
    };
    responses: {
      /** @description Request fulfilled, document follows */
      200: {
        headers: {
        };
        content: never;
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        content: {
          "application/json": {
            detail: string;
            extra?: null | {
              [key: string]: unknown;
            } | unknown[];
            status_code: number;
          };
        };
      };
    };
  };
  /** HeadHandler */
  FilePathHeadHandler: {
    parameters: {
      path: {
        file_path: unknown;
      };
    };
    responses: {
      /** @description Request fulfilled, document follows */
      200: {
        headers: {
        };
        content: never;
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        content: {
          "application/json": {
            detail: string;
            extra?: null | {
              [key: string]: unknown;
            } | unknown[];
            status_code: number;
          };
        };
      };
    };
  };
}
