{
 "title": "Regression Performance",
 "time": { "from": "2022-02-14T17:42:52.719Z", "to": "2022-02-14T18:21:06.642Z" },
 "templating": {
  "list": [
   {
    "name": "feature",
    "query": {
     "query": "label_values(evidently:regression_performance:feature_error_bias, feature)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ME",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "evidently:regression_performance:quality{dataset=\"current\", metric=\"mean_error\"}",
     "legendFormat": "ME"
    }
   ]
  },
  {
   "title": "MAE",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "evidently:regression_performance:quality{dataset=\"current\", metric=\"mean_abs_error\"}",
     "legendFormat": "ME"
    }
   ]
  },
  {
   "title": "MAPE",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "evidently:regression_performance:quality{dataset=\"current\", metric=\"mean_abs_perc_error\"}"
    }
   ]
  },
  {
   "title": "Aggregated Metrics in time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "evidently:regression_performance:quality{dataset=\"current\", metric=\"mean_error\"}",
     "legendFormat": "ME"
    },
    {
     "expr": "evidently:regression_performance:quality{dataset=\"current\", metric=\"mean_abs_error\"}",
     "legendFormat": "MAE"
    },
    {
     "expr": "evidently:regression_performance:quality{dataset=\"current\", metric=\"mean_abs_perc_error\"}",
     "legendFormat": "MAPE"
    }
   ]
  },
  { "title": "Feature error bias", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Error Bias: $feature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "repeat": "feature",
   "targets": [
    {
     "expr": "evidently:regression_performance:feature_error_bias{feature=\"${feature:raw}\", metric=\"current_over\"}",
     "legendFormat": "Overperformance"
    },
    {
     "expr": "evidently:regression_performance:feature_error_bias{feature=\"${feature:raw}\", metric=\"current_under\"}",
     "legendFormat": "Underperformance"
    },
    {
     "expr": "evidently:regression_performance:feature_error_bias{feature=\"${feature:raw}\", metric=\"current_majority\"}",
     "legendFormat": "Majority"
    }
   ]
  }
 ]
}