"""Available tests for TestSuite reports.
Tests grouped into modules.
For detailed information see module documentation.
"""

from .classification_performance_tests import (
    TestAccuracyScore,
    TestF1ByClass,
    TestF1Score,
    TestFNR,
    TestFPR,
    TestLogLoss,
    TestPrecisionByClass,
    TestPrecisionScore,
    TestRecallByClass,
    TestRecallScore,
    TestRocAuc,
    TestTNR,
    TestTPR,
)
from .data_drift_tests import (
    TestAllFeaturesValueDrift,
    TestColumnDrift,
    TestCustomFeaturesValueDrift,
    TestNumberOfDriftedColumns,
    TestShareOfDriftedColumns,
)
from .data_integrity_tests import (
    TestAllColumnsShareOfMissingValues,
    TestColumnAllConstantValues,
    TestColumnAllUniqueValues,
    TestColumnNumberOfDifferentMissingValues,
    TestColumnNumberOfMissingValues,
    TestColumnRegExp,
    TestColumnShareOfMissingValues,
    TestColumnsType,
    TestNumberOfColumns,
    TestNumberOfColumnsWithMissingValues,
    TestNumberOfConstantColumns,
    TestNumberOfDifferentMissingValues,
    TestNumberOfDuplicatedColumns,
    TestNumberOfDuplicatedRows,
    TestNumberOfEmptyColumns,
    TestNumberOfEmptyRows,
    TestNumberOfMissingValues,
    TestNumberOfRows,
    TestNumberOfRowsWithMissingValues,
    TestShareOfColumnsWithMissingValues,
    TestShareOfMissingValues,
    TestShareOfRowsWithMissingValues,
)
from .data_quality_tests import (
    TestAllColumnsMostCommonValueShare,
    TestCatColumnsOutOfListValues,
    TestColumnQuantile,
    TestColumnValueMax,
    TestColumnValueMean,
    TestColumnValueMedian,
    TestColumnValueMin,
    TestColumnValueStd,
    TestConflictPrediction,
    TestConflictTarget,
    TestCorrelationChanges,
    TestHighlyCorrelatedColumns,
    TestMeanInNSigmas,
    TestMostCommonValueShare,
    TestNumberOfOutListValues,
    TestNumberOfOutRangeValues,
    TestNumberOfUniqueValues,
    TestNumColumnsMeanInNSigmas,
    TestNumColumnsOutOfRangeValues,
    TestPredictionFeaturesCorrelations,
    TestShareOfOutListValues,
    TestShareOfOutRangeValues,
    TestTargetFeaturesCorrelations,
    TestTargetPredictionCorrelation,
    TestUniqueValuesShare,
    TestValueList,
    TestValueRange,
)
from .regression_performance_tests import (
    TestValueAbsMaxError,
    TestValueMAE,
    TestValueMAPE,
    TestValueMeanError,
    TestValueR2Score,
    TestValueRMSE,
)
