FROM python:3.11-slim-bookworm
ARG BUILD_DATE
ARG VCS_REF
ARG VERSION
LABEL org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.name="Evidently AI Service" \
      org.label-schema.url="https://github.com/evidentlyai/evidently" \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.vcs-url="https://github.com/evidentlyai/evidently" \
      org.label-schema.version=$VERSION \
      org.label-schema.schema-version="1.0"
LABEL maintainer="mike0sv@evidentlyai.com"


RUN apt-get update && \
    apt-get install -y \
        build-essential \
        make \
        gcc

WORKDIR /src
COPY setup.py .
COPY README.md .
COPY src ./src

RUN pip install . \
    && rm -rf /src

WORKDIR /app
CMD ["evidently", "ui", "--host", "0.0.0.0"]
