name: Build and deploy documentation
runs:
  using: "composite"
  steps:
    - name: 📦 Setup node and pnpm install
      uses: ./.github/share-actions/setup-node-and-pnpm-install

    - name: 🔧 Run generation
      run: pnpm run-all
      shell: bash

    - name: 🚀 Push API reference documentation
      uses: ./.github/share-actions/commit-and-push
