datasets:
  bike_random_forest:
    column_mapping:
      categorical_features:
      - season
      - holiday
      - weekday
      - workingday
      - weathersit
      numerical_features:
      - mnth
      - temp
      - atemp
      - hum
      - windspeed
      target: cnt
    data_format:
      header: true
      separator: ','
    monitors:
      - data_drift
      - regression_performance
      - num_target_drift
  bike_gradient_boosting:
    column_mapping:
      categorical_features:
        - season
        - holiday
        - weekday
        - workingday
        - weathersit
      numerical_features:
        - mnth
        - temp
        - atemp
        - hum
        - windspeed
      target: cnt
    data_format:
      header: true
      separator: ','
    monitors:
      - data_drift
      - regression_performance
      - num_target_drift
  kdd_k_neighbors_classifier:
    column_mapping:
      categorical_features: [ ]
      numerical_features:
        - num_file_creations
        - same_srv_rate
        - num_failed_logins
        - count
        - logged_in
        - wrong_fragment
        - diff_srv_rate
        - dst_host_serror_rate
        - dst_host_rerror_rate
        - src_bytes
        - num_compromised
        - srv_diff_host_rate
        - dst_host_same_src_port_rate
        - dst_host_srv_serror_rate
        - serror_rate
        - num_outbound_cmds
        - num_root
        - dst_host_srv_count
        - dst_host_srv_diff_host_rate
        - root_shell
        - num_access_files
        - rerror_rate
        - dst_bytes
        - is_host_login
        - urgent
        - srv_rerror_rate
        - srv_serror_rate
        - num_shells
        - srv_count
        - dst_host_count
        - duration
        - dst_host_same_srv_rate
        - dst_host_diff_srv_rate
        - is_guest_login
        - land
        - su_attempted
        - hot
        - dst_host_srv_rerror_rate
      target: labels
    data_format:
      header: true
      separator: ','
    monitors:
      - data_drift
      - classification_performance
      - cat_target_drift
service:
  calculation_period_sec: 2
  min_reference_size: 30
  moving_reference: false
  datasets_path: datasets
  use_reference: true
  window_size: 5
