name: UI install
inputs:
  args:
    type: string
    description: ""
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v3
      with:
        version: 9

    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: "pnpm"
        cache-dependency-path: ui/pnpm-lock.yaml

    - name: 📥 Install node dependencies
      working-directory: ui
      run: pnpm i --frozen-lockfile --ignore-scripts ${{ inputs.args }}
      shell: bash
