version: "3.9"
services:

  prefect:
    build:
      context: .
      args:
        USER_ID: ${USER_ID:-1000}
    image: evidently-monitoring-ui
    container_name: prefect
    command: "prefect server start"
    restart: always
    volumes:
      - ./:/home/evidently-monitoring-ui
    environment:
      - PREFECT_HOME=/home/evidently-monitoring-ui/prefect
      - PREFECT_ORION_API_HOST=0.0.0.0
    ports:
      - 4200:4200
    networks:
      - monitoring
  
  evidently-ui:
    build:
      context: .
      args:
        USER_ID: ${USER_ID:-1000}
    image: evidently-monitoring-ui
    container_name: evidently-ui
    command: "evidently ui --workspace evidently --port 8001"
    restart: always
    volumes:
      - ./:/home/evidently-monitoring-ui
    ports:
      - 8001:8001
    networks:
      - monitoring


networks:
  monitoring:
    name: monitoring
