{
 "title": "Chatbot evals",
 "time": { "from": "2025-07-29T18:43:30.117Z", "to": "2025-07-29T18:44:28.766Z" },
 "panels": [
  {
   "title": "Input tokens",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(input_tokens) FROM llm_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Output tokens",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(output_tokens) FROM llm_metrics LIMIT 50 "
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT question FROM llm_metrics LIMIT 50 "
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT response FROM llm_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Response: sentiment score",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT $__time(\"timestamp\"), sentiment FROM llm_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Response: number of sentences",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT sentence_count, $__time(\"timestamp\") FROM llm_metrics LIMIT 50 "
    }
   ]
  }
 ]
}