name: Download artifacts
runs:
  using: "composite"
  steps:
    - name: 游닌 Download API reference artifact
      uses: actions/download-artifact@v4
      with:
        name: api-reference
        path: ./artifacts/api-reference
        github-token: ${{ secrets.GITHUB_TOKEN }}
        run-id: ${{ github.event.workflow_run.id }}
        continue-on-error: true

    - name: 游닌 Download pytest-html-report artifact
      uses: actions/download-artifact@v4
      with:
        name: pytest-html-report
        path: ./artifacts/pytest-html-report
        github-token: ${{ secrets.GITHUB_TOKEN }}
        run-id: ${{ github.event.workflow_run.id }}
        continue-on-error: true

    - name: 游닌 Download UI service playwright report artifact
      uses: actions/download-artifact@v4
      with:
        name: ui-service-playwright-report
        path: ./artifacts/ui-service-playwright-report
        github-token: ${{ secrets.GITHUB_TOKEN }}
        run-id: ${{ github.event.workflow_run.id }}
        continue-on-error: true

    - name: 游닌 Download UI HTML visual testing playwright report artifact
      uses: actions/download-artifact@v4
      with:
        name: ui-html-visual-testing-playwright-report
        path: ./artifacts/ui-html-visual-testing-playwright-report
        github-token: ${{ secrets.GITHUB_TOKEN }}
        run-id: ${{ github.event.workflow_run.id }}
        continue-on-error: true
