services:
  collector:
    image: evidently/evidently-service:0.4.33
    entrypoint: ["evidently", "collector"]
    command: ["--config-path", "/config/collector.json"]
    ports:
      - 8001:8001
    volumes:
      - ./config:/config  # persistent storage for collector configuration.
                          # After updating it via API it would be saved in this folder persistently.
  ui:
    image: evidently/evidently-service:0.4.33
    ports:
      - 8000:8000
    command: ["--workspace", "/data"]
    volumes:
      - data:/data  # where to store data for UI service. In this example is docker volume.
volumes:
  data: