{
 "title": "Data Quality",
 "time": { "from": "2021-02-01T01:00:00.000Z", "to": "2021-02-01T13:00:00.000Z" },
 "refresh": "10s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Data Quality Monitoring\n\n  Here can be your information about dashboard and its usage.\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "General information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Dataset Drift",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "legendFormat": "dataset drift",
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  dataset_drift::int\nFROM data_quality\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Share of drifted features",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "legendFormat": "share",
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  share_of_drifted_columns\nFROM data_quality\nORDER BY 1"
    }
   ]
  },
  {
   "title": "# of drifted features",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "legendFormat": "Drifted",
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  number_of_drifted_columns\nFROM data_quality\nORDER BY 1"
    }
   ]
  },
  {
   "title": "# of features",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "legendFormat": "Total",
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  ds_drift_metric_number_of_columns\nFROM data_quality\nORDER BY 1"
    }
   ]
  }
 ]
}