{
 "title": "Prediction Drift",
 "time": { "from": "2021-02-01T01:00:00.000Z", "to": "2021-02-01T13:00:00.000Z" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Stat Test",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  MAX(stattest_name)\nFROM\n  prediction_drift"
    }
   ]
  },
  {
   "title": "Threshold",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  threshold\nFROM\n  prediction_drift\n"
    }
   ]
  },
  {
   "title": "Percentage of Drifts",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(drift_detected::int) AS \"COUNT DRIFTS\" FROM prediction_drift LIMIT 50 "
    },
    {
     "rawSql": "SELECT COUNT(drift_detected) AS \"TOTAL\" FROM prediction_drift LIMIT 50 "
    },
    { "expression": "$A / $B * 100", "type": "math" }
   ]
  },
  {
   "title": "Drifts Detected Timeline",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  drift_detected::int\nFROM\n  prediction_drift\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Drift Score (p-value)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "legendFormat": "{{kind}}",
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  drift_score, threshold\nFROM prediction_drift\nORDER BY 1"
    }
   ]
  }
 ]
}